import { Router } from 'express';
import { ObjectId } from 'mongodb';

const scopes = ['production', 'local_test'];
const statuses = ['pending', 'active', 'paused', 'blocked', 'expired', 'draft'];
const asId = (value) => ObjectId.isValid(value) ? new ObjectId(value) : null;
const safeDate = (value) => value instanceof Date ? value : value ? new Date(value) : null;

function adminOnly(authMiddleware) { return [authMiddleware.requireAuth, authMiddleware.requireRole('admin')]; }
function audit(db, actor, action, entityType, entityId, scope, changes) { return db.collection('auditEvents').insertOne({ actorUserId: actor._id, action, entityType, entityId: String(entityId), scope, changes, timestamp: new Date() }); }
function providerView(profile, user, offerCount = 0) { return { id: String(profile._id), userId: String(profile.userId), businessName: profile.businessName || profile.displayName || null, email: user?.emailNormalized || profile.contactEmail || null, phone: profile.phone || null, website: profile.website || null, status: profile.status || 'pending', scope: profile.scope || 'production', location: profile.location || null, offerCount, createdAt: profile.createdAt, updatedAt: profile.updatedAt }; }
function offerView(offer, provider) { return { id: String(offer._id), title: offer.title, status: offer.status, scope: offer.scope, providerId: String(offer.providerId), providerName: provider?.businessName || provider?.displayName || null, needKeys: offer.needKeys || [], price: offer.price, availability: offer.availability, radiusMeters: offer.radiusMeters, images: offer.images || [], location: provider?.location || null, lastConfirmedAt: offer.lastConfirmedAt, confirmationDueAt: offer.confirmationDueAt, updatedAt: offer.updatedAt }; }

export function createAdminRouter(databaseService, authMiddleware) {
  const router = Router();
  const guard = adminOnly(authMiddleware);
  const dbRequired = (res) => { const db = databaseService.getDb(); if (!db) { res.status(503).json({ ok: false, status: 'database_unavailable' }); return null; } return db; };
  router.get('/overview', ...guard, async (req, res) => { const db = dbRequired(res); if (!db) return; const scope = scopes.includes(req.query.scope) ? req.query.scope : 'production'; const [profiles, offers, needs, quality] = await Promise.all([db.collection('providerProfiles').find({ scope }).toArray(), db.collection('offers').find({ scope }).toArray(), db.collection('needs').find({}).sort({ sortOrder: 1, key: 1 }).toArray(), db.collection('providerProfiles').countDocuments({ scope, $or: [{ location: null }, { location: { $exists: false } }] })]); const counts = (items, field = 'status') => items.reduce((out, item) => { out[item[field] || 'unknown'] = (out[item[field] || 'unknown'] || 0) + 1; return out; }, {}); return res.json({ ok: true, scope, providers: counts(profiles), offers: counts(offers), needs: { total: needs.length, active: needs.filter((need) => need.status === 'active').length }, quality: { providersWithoutLocation: quality } }); });
  router.get('/providers', ...guard, async (req, res) => { const db = dbRequired(res); if (!db) return; const scope = scopes.includes(req.query.scope) ? req.query.scope : 'production'; const filter = { scope }; if (statuses.includes(req.query.status)) filter.status = req.query.status; const search = String(req.query.search || '').trim().toLowerCase(); const profiles = await db.collection('providerProfiles').find(filter).sort({ updatedAt: -1 }).toArray(); const users = await db.collection('users').find({ _id: { $in: profiles.map((profile) => profile.userId) } }).toArray(); const offers = await db.collection('offers').find({ scope, providerId: { $in: profiles.map((profile) => profile.userId) } }).toArray(); const items = profiles.map((profile) => providerView(profile, users.find((user) => String(user._id) === String(profile.userId)), offers.filter((offer) => String(offer.providerId) === String(profile.userId)).length)).filter((item) => !search || `${item.businessName} ${item.email}`.toLowerCase().includes(search)); return res.json({ ok: true, scope, items }); });
  router.get('/offers', ...guard, async (req, res) => { const db = dbRequired(res); if (!db) return; const scope = scopes.includes(req.query.scope) ? req.query.scope : 'production'; const filter = { scope }; if (statuses.includes(req.query.status)) filter.status = req.query.status; const offers = await db.collection('offers').find(filter).sort({ updatedAt: -1 }).toArray(); const profiles = await db.collection('providerProfiles').find({ scope, userId: { $in: offers.map((offer) => offer.providerId) } }).toArray(); const items = offers.map((offer) => offerView(offer, profiles.find((profile) => String(profile.userId) === String(offer.providerId)))); return res.json({ ok: true, scope, items }); });
  router.get('/needs', ...guard, async (req, res) => { const db = dbRequired(res); if (!db) return; const items = await db.collection('needs').find({}).sort({ sortOrder: 1, key: 1 }).toArray(); return res.json({ ok: true, items }); });
  router.get('/quality', ...guard, async (req, res) => { const db = dbRequired(res); if (!db) return; const scope = scopes.includes(req.query.scope) ? req.query.scope : 'production'; const [profiles, offers, needs] = await Promise.all([db.collection('providerProfiles').find({ scope }).toArray(), db.collection('offers').find({ scope }).toArray(), db.collection('needs').find({}).toArray()]); const activeKeys = new Set(needs.filter((need) => need.status === 'active').map((need) => need.key)); const issues = []; profiles.forEach((profile) => { if (!profile.location?.location?.coordinates && !profile.location?.coordinates) issues.push({ type: 'provider_location_missing', entityId: String(profile._id), scope, label: profile.businessName || profile.displayName }); }); offers.forEach((offer) => { if (!offer.needKeys?.length || offer.needKeys.some((key) => !activeKeys.has(key))) issues.push({ type: 'offer_needs_invalid', entityId: String(offer._id), scope, label: offer.title }); if (!Number.isFinite(offer.radiusMeters) || offer.radiusMeters < 50 || offer.radiusMeters > 1000) issues.push({ type: 'offer_radius_invalid', entityId: String(offer._id), scope, label: offer.title }); if (safeDate(offer.confirmationDueAt)?.getTime() < Date.now()) issues.push({ type: 'offer_confirmation_expired', entityId: String(offer._id), scope, label: offer.title }); }); return res.json({ ok: true, scope, items: issues }); });
  router.post('/providers/:id/status', ...guard, async (req, res) => { const db = dbRequired(res); if (!db) return; const id = asId(req.params.id); const status = String(req.body?.status || ''); if (!id || !statuses.includes(status)) return res.status(400).json({ ok: false, status: 'invalid_status' }); const scope = scopes.includes(req.body?.scope) ? req.body.scope : 'production'; const result = await db.collection('providerProfiles').findOneAndUpdate({ _id: id, scope }, { $set: { status, updatedAt: new Date() } }, { returnDocument: 'after' }); if (!result) return res.status(404).json({ ok: false, status: 'provider_not_found' }); await audit(db, req.user, 'provider_status_changed', 'providerProfile', id, scope, { status }); return res.json({ ok: true, status: 'updated', item: result }); });
  router.post('/offers/:id/status', ...guard, async (req, res) => { const db = dbRequired(res); if (!db) return; const id = asId(req.params.id); const status = String(req.body?.status || ''); if (!id || !statuses.includes(status)) return res.status(400).json({ ok: false, status: 'invalid_status' }); const scope = scopes.includes(req.body?.scope) ? req.body.scope : 'production'; const result = await db.collection('offers').findOneAndUpdate({ _id: id, scope }, { $set: { status, updatedAt: new Date() } }, { returnDocument: 'after' }); if (!result) return res.status(404).json({ ok: false, status: 'offer_not_found' }); await audit(db, req.user, 'offer_status_changed', 'offer', id, scope, { status }); return res.json({ ok: true, status: 'updated', item: result }); });
  router.patch('/needs/:key', ...guard, async (req, res) => {
    const db = dbRequired(res); if (!db) return;
    const key = String(req.params.key || '').trim();
    if (!key) return res.status(400).json({ ok: false, status: 'invalid_need_key' });
    const allowed = ['status', 'labels', 'pushable', 'criticality', 'sortOrder'];
    const changes = Object.fromEntries(Object.entries(req.body || {}).filter(([field]) => allowed.includes(field)));
    if (!Object.keys(changes).length) return res.status(400).json({ ok: false, status: 'no_supported_changes' });
    if (changes.status !== undefined && !['active', 'inactive'].includes(changes.status)) return res.status(400).json({ ok: false, status: 'invalid_need_status' });
    if (changes.labels !== undefined && (!changes.labels || typeof changes.labels !== 'object')) return res.status(400).json({ ok: false, status: 'invalid_need_labels' });
    if (changes.pushable !== undefined && typeof changes.pushable !== 'boolean') return res.status(400).json({ ok: false, status: 'invalid_need_pushable' });
    const result = await db.collection('needs').findOneAndUpdate({ key }, { $set: { ...changes, updatedAt: new Date() } }, { returnDocument: 'after' });
    if (!result) return res.status(404).json({ ok: false, status: 'need_not_found' });
    await audit(db, req.user, 'need_updated', 'need', key, 'global', changes);
    return res.json({ ok: true, status: 'updated', item: result });
  });
  return router;
}
